
from . import main


test_string = open("./saves/100CompletedSaveFile", "rt")
test_string = test_string.readline()


def test_chest_parser():

    """ test the chest_Content_Dict() function """

    assert main.chest_Content_Dict(test_string) == {'WateringCan': 4,
                                                    'Scythe': 4,
                                                    'GrassStarter': 78,
                                                    'PrismaticShard': 1,
                                                    'BoneFragment': 40,
                                                    'Coal': 45,
                                                    'CopperBar': 104,
                                                    'GoldBar': 97,
                                                    'IridiumBar': 95,
                                                    'IridiumOre': 3,
                                                    'IronBar': 100,
                                                    'RadioactiveBar': 100,
                                                    'Clay': 490,
                                                    'Hardwood': 452,
                                                    'Stone': 130,
                                                    'Wood': 50,
                                                    'SolarEssence': 49,
                                                    'Acorn': 97,
                                                    'MapleSeed': 97,
                                                    'PineCone': 97,
                                                    'GoatMilk': 4,
                                                    'Milk': 6,
                                                    'VoidEgg': 3,
                                                    'Egg': 59,
                                                    'DuckEgg': 2,
                                                    'Wool': 1,
                                                    'GoldenEgg': 1,
                                                    'SturgeonRoe': 7,
                                                    'Hops': 520,
                                                    'Grape': 520,
                                                    'Salmonberry': 424,
                                                    'Blackberry': 520,
                                                    'ParsnipSeeds': 45,
                                                    'Axe': 3,
                                                    'Hoe': 3,
                                                    'Pickaxe': 3,
                                                    'Cauliflower': 20,
                                                    'Garlic': 20,
                                                    'GreenBean': 20,
                                                    'Kale': 20,
                                                    'Parsnip': 20,
                                                    'Potato': 20,
                                                    'Rhubarb': 20,
                                                    'Strawberry': 20,
                                                    'BlueJazz': 20,
                                                    'Tulip': 20,
                                                    'Dandelion': 20,
                                                    'Leek': 20,
                                                    'WildHorseradish': 50,
                                                    'Corn': 20,
                                                    'FiddleheadFern': 50,
                                                    'Radish': 20,
                                                    'RedCabbage': 20,
                                                    'Tomato': 20,
                                                    'Blueberry': 20,
                                                    'HotPepper': 20,
                                                    'Melon': 20,
                                                    'Starfruit': 20,
                                                    'Poppy': 20,
                                                    'SummerSpangle': 20,
                                                    'Oil': 50,
                                                    'Rice': 100,
                                                    'Sugar': 55,
                                                    'Vinegar': 60,
                                                    'WheatFlour': 100,
                                                    'LargeMilk': 50,
                                                    'Bread': 100,
                                                    'FriedEgg': 50,
                                                    'Hashbrowns': 50,
                                                    'Omelet': 50,
                                                    'Pancakes': 50,
                                                    'Tortilla': 50,
                                                    'Cheese': 50,
                                                    'DinosaurMayonnaise': 50,
                                                    'DuckMayonnaise': 50,
                                                    'GoatCheese': 50,
                                                    'Mayonnaise': 50,
                                                    'TruffleOil': 50,
                                                    'VoidMayonnaise': 50,
                                                    'MapleSyrup': 20,
                                                    'ANightOnEco-Hill': 1,
                                                    'Skeleton': 1,
                                                    'SlothSkeletonL': 1,
                                                    'SlothSkeletonM': 1,
                                                    'SlothSkeletonR': 1,
                                                    'BlueCowboyHat': 1,
                                                    'Tropiclip': 1,
                                                    'GreenAlgae': 50,
                                                    'Seaweed': 50,
                                                    'WhiteAlgae': 50,
                                                    'Bream': 20,
                                                    'Carp': 20,
                                                    'Crab': 20,
                                                    'Crayfish': 20,
                                                    'Eel': 20,
                                                    'Flounder': 20,
                                                    'LargemouthBass': 20,
                                                    'Lobster': 20,
                                                    'MidnightCarp': 20,
                                                    'Mussel': 20,
                                                    'Periwinkle': 20,
                                                    'RainbowTrout': 20,
                                                    'Salmon': 20,
                                                    'Sardine': 20,
                                                    'SeaCucumber': 20,
                                                    'Shrimp': 20,
                                                    'Snail': 20,
                                                    'Squid': 20,
                                                    'Sunfish': 20,
                                                    'Tuna': 20,
                                                    'Clam': 50,
                                                    'SquidInk': 20,
                                                    'TaroRoot': 40,
                                                    'AncientFruit': 20,
                                                    'Apple': 20,
                                                    'Apricot': 20,
                                                    'Banana': 20,
                                                    'CactusFruit': 20,
                                                    'Coconut': 20,
                                                    'Mango': 20,
                                                    'Pineapple': 20,
                                                    'CaveCarrot': 50,
                                                    'CommonMushroom': 20,
                                                    'Ginger': 52,
                                                    'Morel': 20,
                                                    'WinterRoot': 50,
                                                    'Amaranth': 20,
                                                    'Artichoke': 20,
                                                    'Beet': 20,
                                                    'BokChoy': 20,
                                                    'Eggplant': 20,
                                                    'Pumpkin': 20,
                                                    'Yam': 20,
                                                    'Cranberries': 20,
                                                    'WildPlum': 20,
                                                    'FairyRose': 20,
                                                    'Hazelnut': 20,
                                                    'UnmilledRice': 11,
                                                    'AncientSeeds': 6,
                                                    'HyperSpeed-Gro': 381,
                                                    'MagmaCap': 13,
                                                    'DragonTooth': 9,
                                                    'BlueDiscus': 1,
                                                    'CinderShard': 52}


def test_recipe_parser():

    """ test the make_Player_Food_Dict() function """

    assert main.make_Player_Food_Dict(test_string) == {'FriedEgg': '0',
                                                       'SurvivalBurger': '0',
                                                       'StirFry': '0',
                                                       'Coleslaw': '0',
                                                       "Farmer'sLunch": '0',
                                                       'RadishSalad': '0',
                                                       'Omelet': '0',
                                                       "Miner'sTreat": '0',
                                                       "Disho'TheSea": '0',
                                                       'BakedFish': '0',
                                                       'Pancakes': '0',
                                                       'RootsPlatter': '0',
                                                       'MakiRoll': '0',
                                                       'Bread': '0',
                                                       'Tortilla': '0',
                                                       'TroutSoup': '0',
                                                       'GlazedYams': '0',
                                                       'ArtichokeDip': '0',
                                                       'PlumPudding': '0',
                                                       'ChocolateCake': '0',
                                                       'Sashimi': '0',
                                                       'PumpkinPie': '0',
                                                       'Hashbrowns': '0',
                                                       'Pizza': '0',
                                                       'CranberryCandy': '0',
                                                       'ParsnipSoup': '0',
                                                       'CheeseCauli.': '0',
                                                       'CompleteBreakfast': '0',
                                                       'TripleShotEspresso': '0',
                                                       'LuckyLunch': '0',
                                                       'CarpSurprise': '0',
                                                       'SeafoamPudding': '0',
                                                       'CrispyBass': '0',
                                                       'MapleBar': '0',
                                                       'FriedMushroom': '0',
                                                       'Salad': '0',
                                                       'FriedEel': '0',
                                                       'PinkCake': '0',
                                                       'AlgaeSoup': '0',
                                                       'Spaghetti': '0',
                                                       'Chowder': '0',
                                                       'Escargot': '0',
                                                       'RoastedHazelnuts': '0',
                                                       'PepperPoppers': '0',
                                                       'FishTaco': '0',
                                                       'FruitSalad': '0',
                                                       'SalmonDinner': '0',
                                                       'PaleBroth': '0',
                                                       'Cookies': '0',
                                                       'VegetableStew': '0',
                                                       'FriedCalamari': '0',
                                                       'BlackberryCobbler': '0',
                                                       'Stuffing': '0',
                                                       'EggplantParm.': '0',
                                                       'FishStew': '0',
                                                       'CrabCakes': '0',
                                                       'PumpkinSoup': '0',
                                                       "Autumn'sBounty": '0',
                                                       'RedPlate': '0',
                                                       'SuperMeal': '0',
                                                       'SpicyEel': '0',
                                                       'RicePudding': '0',
                                                       'IceCream': '0',
                                                       'BeanHotpot': '0',
                                                       'BlueberryTart': '0',
                                                       'RhubarbPie': '0',
                                                       'LobsterBisque': '0',
                                                       'FiddleheadRisotto': '0',
                                                       'PoppyseedMuffin': '0',
                                                       'StrangeBun': '0',
                                                       'TomKhaSoup': '0',
                                                       'Cran.Sauce': '0',
                                                       'Bruschetta': '0',
                                                       'ShrimpCocktail': '0',
                                                       'SquidInkRavioli': '0',
                                                       'GingerAle': '0',
                                                       'BananaPudding': '0',
                                                       'TropicalCurry': '0',
                                                       'Poi': '0',
                                                       'MangoStickyRice': '0'}


def test_recipe_comparer():

    """ test the still_missing() function """

    test_player = {"Stuff": 1,
                   "Things": 3,
                   "Objects": 5}
    test_archive = {"Stuff": {"Filled": 1,
                              "With": 5,
                              "Things": 8},
                    "Things": {"Very": 5,
                               "Important": 7,
                               "Text": 1},
                    "Objects": {"Shorter": 3},
                    "Different": {"Just": 2,
                                  "Two": 2},
                    "Unneeded": {"Some": 4,
                                 "More": 2,
                                 "Content": 3},
                    "Filler": {"AlmostDone": 1,
                               "It'sContent": 5,
                               "CoolStuffBoi": 6},
                    "Text": {"Its": 4,
                             "Even": 1,
                             "Moore": 23,
                             "IKnowItsSpelledWrongItsIntended": 18}}

    assert main.still_missing(test_player, test_archive) == ["Stuff", "Things", "Objects"]
